name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .[tester,linter,mypy,formatter]
      - name: Pre-commit
        run: |
          pre-commit run --all-files --show-diff-on-failure
      - name: Tests
        run: |
          pytest -q
